# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /#top
    weight: 10
  - name: Members
    url: /#members
    weight: 20
    hasChildren: true
  - name: Institutions
    url: /institutions/
    parent: Members
    weight: 30
  - name: Representatives
    url: /representatives/
    parent: Members
    weight: 30
  - name: Congress
    url: /#congress
    weight: 30
    hasChildren: true
  - name: PRIMA 2022
    url: /congress/prima2022/
    parent: Congress
    weight: 10
  - name: PRIMA 2017
    url: /congress/prima2017/
    parent: Congress
    weight: 20
  - name: PRIMA 2013
    url: /congress/prima2013/
    parent: Congress
    weight: 30
  - name: PRIMA 2009
    url: /congress/prima2009/
    parent: Congress
    weight: 40
  - name: About
    weight: 40
    url: /#about
  - name: Contact
    weight: 50
